-- The Dirt Archive starter seed
-- Review before running against production Supabase.
-- This seed is intentionally limited to public historical catalog data.

insert into builders (builder_id, name, country, description) values ('BLD-0001', 'Dallas-Arbiter', 'UK', 'Dallas-Arbiter is the principal original branding/manufacturing entity used for the Fuzz Face founding record.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0002', 'Sola Sound', 'UK', 'Foundational British fuzz builder/OEM behind Tone Bender-family products and multiple branded versions.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0003', 'Electro-Harmonix', 'USA', 'Manufacturer behind the Big Muff family and numerous later variants/reissues.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0004', 'Ibanez / Hoshino', 'Japan', 'Retail/brand lineage associated with Tube Screamer models; Maxon manufactured foundational Japanese examples.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0005', 'Maxon', 'Japan', 'Manufacturer/designer lineage central to the OD808/Tube Screamer family.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0006', 'ProCo', 'USA', 'Manufacturer of the RAT family; founding model history begins in the late 1970s.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0007', 'Vox', 'UK / Italy', 'Brand that sold multiple Tone Bender-family products, including Sola Sound-built British MKII/MKIII products and Italian-made model V828.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0008', 'Rotosound', 'UK', 'British brand supplied with Sola Sound fuzz products, including multiple generations of the Rotosound Fuzz Box.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0009', 'Park', 'UK', 'Marshall-associated brand whose Fuzz Sound was supplied by Sola Sound in Tone Bender-family forms.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0010', 'Marshall', 'UK', 'Amplifier company whose early SupaFuzz was supplied by Sola Sound and later produced by Marshall itself.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0011', 'Carlsbro', 'UK', 'British amplifier/effects company with an early 1966 Fuzz-Tone and later Sola Sound-supplied fuzz products.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0012', 'D*A*M', 'UK', 'Boutique builder with an extensive Tone Bender / fuzz-focused catalog and documented reissues of classic designs.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0013', 'Basic Audio', 'USA', 'John Lyons'' Fayetteville, West Virginia pedal company; began making pedals in 1998 and has a large fuzz-oriented catalog.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0014', 'Monsterpiece Fuzz', 'USA', 'One-person handmade boutique fuzz builder with a documented family of germanium and silicon fuzzes.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0015', 'Blackout Effectors', 'Canada / USA', 'Founded by Kyle Tompkins in Vancouver in 2008 and moved to Asheville, North Carolina in 2009.') on conflict (builder_id) do nothing;
insert into builders (builder_id, name, country, description) values ('BLD-0016', 'Stomp Under Foot', 'USA', 'Boutique builder specializing heavily in Big Muff and Tone Bender-family recreations plus original fuzz designs.') on conflict (builder_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0001', 'Fuzz Face', 'Fuzz', 'Foundational fuzz pedal with multiple enclosure, branding, color and transistor-technology changes across original British production.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0002', 'Tone Bender', 'Fuzz', 'A broader product family and genealogy than a single simple model; associated with multiple brands and OEM relationships.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0003', 'Big Muff Pi', 'Fuzz', 'A large family spanning multiple major generations, editions, countries and reissues.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0004', 'Tube Screamer', 'Overdrive', 'Family anchored by the OD808 / TS808 lineage and followed by multiple Ibanez generations and later variants.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0005', 'RAT', 'Distortion', 'One of the defining compact distortion families, with Bud Box, Big Box, Small Box, RAT2 and later variations.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0006', 'Tone Bender Professional MKII', 'Fuzz', 'Sola Sound-branded three-transistor Tone Bender MKII. The same basic production lineage was supplied to several OEM brands.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0007', 'Tone Bender Professional MKII', 'Fuzz', 'Vox-branded British Tone Bender Professional MKII supplied by Sola Sound, with early and later cosmetic distinctions.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0008', 'Tone Bender MKIII', 'Fuzz', 'Vox-branded MKIII lineage supplied by Sola Sound; documented two-control, germanium three-control, Hastings and later silicon forms.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0009', 'Tone Bender MKIV', 'Fuzz', 'Sola Sound''s later Tone Bender family, with early ''bendy'' graphics and later ''Batman'' graphics and changing internal technology over the 1970s.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0010', 'Rotosound Fuzz Box', 'Fuzz', 'Rotosound-branded fuzz product supplied by Sola Sound across multiple enclosure, control and circuit periods.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0011', 'Park Fuzz Sound', 'Fuzz', 'Park-branded Sola Sound fuzz product appearing in MKIII- and later MKIV-type forms.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0012', 'Marshall SupaFuzz', 'Fuzz', 'Marshall-branded fuzz first supplied by Sola Sound, with production later taken over by Marshall.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0013', 'Carlsbro Fuzz-Tone', 'Fuzz', 'Early 1966 wedge-shaped Carlsbro Fuzz-Tone followed by a later Sola Sound-supplied three-knob fuzz product.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0014', 'Triangle Big Muff Pi', 'Fuzz', 'Early Big Muff family commonly called the Triangle because of its three-knob layout; later reissued by EHX.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0015', 'Ram''s Head Big Muff Pi', 'Fuzz', 'Major 1970s Big Muff family commonly called Ram''s Head; numerous production variants.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0016', 'Op-Amp Big Muff Pi', 'Fuzz', 'Late-1970s op-amp Big Muff family; distinct from the transistor generations.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0017', 'Sovtek / Russian Big Muff Pi', 'Fuzz', 'Russian branch of the Big Muff family including Red Army Overdrive, Civil War, Green Russian and Black Russian forms.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0018', 'TS808 Tube Screamer', 'Overdrive', 'Ibanez-branded Tube Screamer derived from Maxon''s OD808 production lineage; early and late board/construction details exist.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0019', 'TS9 Tube Screamer', 'Overdrive', 'Ibanez 9-series Tube Screamer with important output/control changes and later component substitutions.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0020', 'TS10 Tube Screamer', 'Overdrive', 'Power Series Tube Screamer with multiple production changes and later Taiwan-made examples.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0021', 'TS5 Tube Screamer', 'Overdrive', 'Plastic Soundtank Tube Screamer produced in Taiwan; related closely to TS9 family.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0022', 'TS7 Tube Screamer', 'Overdrive', 'Tone-Lok era Tube Screamer with HOT mode and Taiwan production.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0023', 'RAT2', 'Distortion', 'Long-running successor in the RAT family; introduced with LED and switching changes.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0024', 'Turbo RAT', 'Distortion', 'RAT-family model with a distinct clipping arrangement and later reissues.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0025', 'You Dirty RAT', 'Distortion', 'RAT-family variant with a distinct production identity; included as a model rather than a RAT revision.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0026', 'Vintage RAT', 'Distortion', 'Limited vintage-style RAT product documented by Pro Co.') on conflict (pedal_id) do nothing;
insert into pedals (pedal_id, model_name, primary_category, description) values ('PED-0027', '1985 Whiteface RAT', 'Distortion', 'Collector-named Small Box Whiteface production form.') on conflict (pedal_id) do nothing;